---
- name: "Add grafana repository."
  ansible.builtin.deb822_repository:
    name: "grafana"
    types: "deb"
    uris: "https://apt.grafana.com"
    suites: stable
    architectures: "amd64"
    signed_by: "https://apt.grafana.com/gpg.key"
    components: "main"
- name: "Install alloy latest version."
  ansible.builtin.apt:
    name:
      - alloy
    update_cache: true
    install_recommends: false
