---
- name: "Ensure socks-proxy application directory."
  ansible.builtin.file:
    name: "/opt/messages/socks-proxy"
    owner: "messages"
    group: "messages"
    mode: "0750"
    state: directory

- name: "Deploy socks-proxy env file."
  ansible.builtin.template:
    src: "{{ st_messages_socks_proxy_env_template }}"
    dest: "/opt/messages/socks-proxy/env"
    owner: "messages"
    group: "messages"
    mode: "0600"
  notify: "systemctl --user restart socks-proxy"

- name: "Create socks-proxy app"
  ansible.builtin.import_role:
    name: suitenumerique.st.podman
    tasks_from: application.yml
  vars:
    st_podman_user: "messages"
    st_podman_application_name: "socks-proxy"
    st_podman_application_compose_template: "{{ st_messages_socks_proxy_compose_template }}"
