---
argument_specs:
  main:
    short_description: "Installs and configures the keycloak application from La Suite Territoriale on Debian systems."
    options:
      st_keycloak_uid:
        type: "int"
        description: "UID of the `keycloak` user, used for the podman role."
        default: 1100
      st_keycloak_gid:
        type: "int"
        description: "GID of the `keycloak` group, used for the podman role."
        default: "{{ st_keycloak_uid }}"
      st_keycloak_enabled:
        type: "bool"
        description: "Triggers the installation of keycloak."
        default: false
      st_keycloak_tag:
        type: "str"
        description: "Tag of the keycloak docker image to deploy."
        default: "latest"
      st_keycloak_dir:
        type: "str"
        description: "Remote path to the base directory for keycloak app."
        default: "/opt/keycloak/keycloak"
      st_keycloak_env_template:
        type: "str"
        description: "Local path to the custom template to use for keycloak env file."
        default: "keycloak/env.j2"
      st_keycloak_env:
        type: "str"
        description: "Content of the default keycloak_env_template, not used if st_keycloak_env_template is defined."
      st_keycloak_compose_template:
        type: "str"
        description: "Local path to the custom template to use for keycloak compose file."
        default: keycloak/compose.yaml.j2
      st_keycloak_port:
        type: "str"
        description: "The port to open on the host, redirecting to port 8080 in the container. It can also specify the ip address, something like 127.0.0.1:8080."
        default: "8080"
      st_keycloak_cadvisor_enabled:
        type: "bool"
        description: "Triggers the installation of the alloy agent, used to send metrics to a Prometheus compatible server and logs to a Loki server."
        default: false
      st_keycloak_cadvisor_port:
        type: "str"
        description: "The host published port of the cadvisor container."
        default: "127.0.0.1:58080"
