---
dependencies: []
galaxy_info:
  role_name: keycloak
  author: La Suite territoriale
  company: Agence Nationale de la Coh√©sion des Territoires
  description: This role deploys a Keycloak instance for La Suite Territoriale applications on a rootless podman base on Debian systems.
  license: MIT
  min_ansible_version: 2.18.0
  issue_tracker_url: https://github.com/suitenumerique/st-ansible/issues
  platforms:
    - name: Debian
      versions:
        - trixie
  galaxy_tags:
    - suiteterritoriale
    - system
